---
name: Build and Push Image

on:
  # we want pull requests so we can build(test) but not push to image registry
  pull_request:
    branches:
      - 'main'
    # only build when important files change
    paths-ignore:
      - 'README.md'
      - '.github/workflows/linter.yml'
      - '.github/linters/**'
  push:
    branches:
      - 'main'
    # only build when important files change
    paths-ignore:
      - 'README.md'
      - '.github/workflows/linter.yml'
      - '.github/linters/**'
  schedule:
    # re-run montly to keep image fesh with upstream base images
    - cron: '0 12 15 * *'
  workflow_dispatch:
    # run whenever we want!
  workflow_call:
    # allow reuse of this workflow in other repos
    inputs:
      dockerhub-username:
        description: Docker Hub username
        required: false
        type: string
        default: bretfisher
      context:
        description: Docker context (path) to start build from
        required: false
        type: string
        default: .
      target:
        description: Build stage to target
        required: false
        type: string
      platforms:
        description: Platforms to build for
        required: false
        type: string
        default: linux/amd64,linux/arm64,linux/arm/v7
      image-names:
        description: A list of the account/repo names for docker build
        required: false
        type: string
        default: |
          ${{ github.repository }}
          ghcr.io/${{ github.repository }}
    secrets:
      dockerhub-token:
        description: Docker Hub token
        required: true


jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.4.0
      -
        # we need qemu and buildx so we can build multiple platforms later
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1.2.0
      -
        # BuildKit (used with `docker buildx`) is the best way to build images
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ inputs.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}
      -
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3.8.0
        with:
          # list of Docker images to use as base name for tags
          images: ${{ inputs.image-names }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=pr,prefix=pr
      -
        # this will build the images, once per platform,
        # then push to both Docker Hub and GHCR
        name: Docker Build and Push
        id: docker_build_and_push
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ inputs.platforms }}
          context: ${{ inputs.context }}
          target: ${{ inputs.target }}
          builder: ${{ steps.buildx.outputs.name }}
          # it uses github cache API for faster builds:
          # https://github.com/crazy-max/docker-build-push-action/blob/master/docs/advanced/cache.md#cache-backend-api
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # for an approved pull_request, only push pr-specific tags
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      -
        name: Show image digest
        run: echo ${{ steps.docker_build_and_push.outputs.digest }}